apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web
  labels:
    app: order-web
spec:
  selector:
    matchLabels:
      app: order-web
  template:
    metadata:
      labels:
        app: order-web
    spec:
      containers:
        - name: order-web
          image: ghcr.io/kedacore/sample-dotnet-worker-servicebus-portal
          env:
            - name: KEDA_SERVICEBUS_QUEUE_CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: secrets-order-portal
                  key: servicebus-connectionstring
---
apiVersion: v1
kind: Service
metadata:
  name: kedasampleweb
  labels:
    app: order-web
  annotations:
    # Expose service on <label-name>.<location>.cloudapp.azure.com
    service.beta.kubernetes.io/azure-dns-label-name: keda-orders-portal
spec:
  selector:
    app: order-web
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-order-portal
  labels:
    app: order-web
data:
  servicebus-connectionstring: "RW5kcG9pbnQ9c2I6Ly9zZXJ2aWNlYnVzbmFtZXNwYWNlMDg5LnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9b3JkZXItY29uc3VtZXI7U2hhcmVkQWNjZXNzS2V5PVNCN3ZmdjBnaTB4SmNaRnhxa1JLYk05UmJDY2pmU1hNODRRRTNxTDlhSFk9O0VudGl0eVBhdGg9b3JkZXJzCg=="
